### ISSUE TITLE
try to update from older bytebuffer version  TypeError: bb.readLString is not a function

### ISSUE THREAD

**Issue by arpu** [ExodusForks/bytebuffer.js#4]
Hey,

any idea why this is not usable anymore (update from old bytebuffer  "bytebuffer": "2.3.2",)

**Comment by RyanZim** [comment]
This is a fork of the original bytebuffer; and you're upgrading from a very old version of bytebuffer; there have been many breaking changes; seems you're calling a function that is not available in the latest version.

**Comment by arpu** [comment]
ok thx a lot for clarification!
